---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "CET-NETWORK"
subtitle: "IT-Tools"
logo: "image/logo.svg"
#icon: "fas fa-solid fa-ethernet" # Optional icon

header: true
footer: '<p>Criado com o auxílio de: <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#131313" #"#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "CET-NETWORK"
  icon: "fa fa-solid fa-skull-crossbones"
  content: "Cyber-hacking-tools.<br /> More info @ <a href='https://github.com/PGodinho/cet-network/wiki' target='_blank'>SEBENTA</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Home"
    icon: "fas fa-solid fa-house"
    url: "#"
  - name: "CET"
    icon: "fa-solid fa-building-flag"
    url: "#cet"
    ;target: "_blank" # optional html a tag target attribute
  - name: "Docs"
    icon: "fa-solid fa-book-skull"
    url: "wiki/site/index.html"
    ;target: "_blank" # optional html a tag target attribute  
  
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Log ON"
    icon: "fa-solid fa-user-gear"
    items:
      - name: "VSCode"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png"
        subtitle: "Live Coding"
        tag: "vscode"
        url: "https://vscode.dev/"
        target: "_blank" # optional html a tag target attribute   
      - name: "Azure"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Microsoft_Azure.svg/2048px-Microsoft_Azure.svg.png"
        subtitle: "Cloud Computing"
        tag: "azure"
        url: "https://portal.azure.com/"  
        target: "_blank" # optional html a tag target attribute
      - name: "CISCO"
        logo: "./assets/tools/cisco.svg"
        subtitle: "ID"
        tag: "cisco"
        url: "https://id.cisco.com/"
        target: "_blank" # optional html a tag target attribute      
####################################################################        
  - name: "Tools"
    icon: "fa-solid fa-screwdriver-wrench"
    items:        
      - name: "Help Desk"
        logo: "./assets/tools/help-desk-service.png"
        subtitle: "Help Desk"
        tag: "help"
        url: "#help_desk" 
      - name: "VSCode"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png"
        subtitle: "Ambiente Integrado de Desenvolvimento"
        tag: "vscode"
        url: "https://code.visualstudio.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Draw.io"
        logo: "assets/tools/drawio_logo.png"
        subtitle: "Diagramas"
        tag: "gráficos"
        url: "https://www.drawio.com/"
        target: "_blank" # optional html a tag target attribute
      - name: "Docs"
        logo: "assets/tools/Markdown-mark.svg"
        subtitle: "MKDocs"
        tag: "markdown"
        url: "https://www.mkdocs.org/"
        target: "_blank" # optional html a tag target attribute             
####################################################################
  - name: "Manual"
    icon: "fas fa-book"
    items:
      - name: "Microsoft WSL"
        logo: "./assets/tools/microsoft_logo_wsl.png"
        subtitle: "WSL"
        tag: "microsoft"
        url: "https://learn.microsoft.com/en-us/windows/wsl/"
        target: "_blank" # optional html a tag target attribute
      - name: "Microsoft VM"
        logo: "./assets/tools/microsoft_logo_docs.png"
        subtitle: "Hyper-V"
        tag: "microsoft"
        url: "https://learn.microsoft.com/en-us/virtualization/?source=docs"
        target: "_blank" # optional html a tag target attribute  
      - name: "Cisco"
        logo: "./assets/tools/cisco.svg"
        subtitle: "Networking Technologies and Protocols"
        tag: "cisco"
        url: "https://www.cisco.com/c/en/us/tech/index.html"
        target: "_blank" # optional html a tag target attribute 
      - name: "Red Hat"
        logo: "./assets/tools/red_hat_logo.svg"
        subtitle: "Networking Guide"
        tag: "redhat"
        url: "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/index"
        target: "_blank" # optional html a tag target attribute         
####################################################################
